### ISSUE TITLE
Music does not play

### ISSUE THREAD

**Issue by Agent-Bosnia** [KaanGaming/UltrakillTimer#1]
The music does not play in-game or in the music preview

**Comment by surytrap** [comment]
happened to me too, both ingame console and bepinex console had nothing to say, it just didnt play and the timer didnt flash (or rather, it was always in flash color)

**Comment by kaangamgimginnka** [comment]
wait. I forgot to add AudioEngineFix as a dependency in the mod page. I strongly apologize for not replying to this any sooner. I will also add the dependency to the mod page very soon.

Here's the link to the AudioEngineFix mod, you need to restart the game once after launching the game with that mod enabled: https://thunderstore.io/package/x753/AudioEngineFix/

By the way, the mod doesn't directly use the AudioEngineFix mod itself but it IS required since the mod uses Unity's AudioSource component to be able to play the sound, therefore it doesn't display any error messages in the logs...

~~maybe i should switch to using the WWise audio system like most other mods and ror2 does but nah~~
